<a href="https://colab.research.google.com/github/mot1122/CNN_model/blob/main/use_pytorch/practice_nn_by_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [7]:
torch.__version__

'1.10.0+cu111'

In [19]:
torch.manual_seed(1)

In [20]:
func1=nn.Linear(3,2)

In [21]:
func1.weight

Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462]], requires_grad=True)

In [22]:
func1.bias

Parameter containing:
tensor([-0.1188,  0.2937], requires_grad=True)

In [23]:
func2=nn.Linear(2,1)

In [24]:
x=torch.tensor([1,2,3],dtype=torch.float32)
x=func1(x)
x

tensor([-0.6667,  0.5164], grad_fn=<AddBackward0>)

In [25]:
x=F.relu(x)
x

tensor([0.0000, 0.5164], grad_fn=<ReluBackward0>)

In [26]:
pred=func2(x)
pred

tensor([0.1514], grad_fn=<AddBackward0>)

In [27]:
y=torch.tensor([1],dtype=torch.float32)
y

tensor([1.])

In [28]:
loss=F.mse_loss(y,pred)

In [29]:
loss

tensor(0.7201, grad_fn=<MseLossBackward0>)