<a href="https://colab.research.google.com/github/mot1122/CNN_model/blob/main/use_pytorch/pred_by_pytorch_lightning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install pytorch-lightning==0.7.1
!pip install pytorch-lightning

In [2]:
import numpy as np
import pandas as pd

In [3]:
!cp /content/drive/MyDrive/data/wine_class.csv .

In [4]:
df=pd.read_csv("wine_class.csv")

In [5]:
df.head()

Class  Alcohol   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0      1    14.23  2.43               15.6        127           2.80   
1      1    13.20  2.14               11.2        100           2.65   
2      1    13.16  2.67               18.6        101           2.80   
3      1    14.37  2.50               16.8        113           3.85   
4      1    13.24  2.87               21.0        118           2.80   

   Flavanoids  Nonflavanoid phenols  Color intensity   Hue  Proline  
0        3.06                  0.28             5.64  1.04     1065  
1        2.76                  0.26             4.38  1.05     1050  
2        3.24                  0.30             5.68  1.03     1185  
3        3.49                  0.24             7.80  0.86     1480  
4        2.69                  0.39             4.32  1.04      735

In [6]:
np.unique(df["Class"],return_counts=True)

(array([1, 2, 3]), array([59, 71, 48]))

In [58]:
X=df.drop("Class",axis=1)
y=df["Class"]

In [59]:
X.head(2)

Alcohol   Ash  Alcalinity of ash  Magnesium  Total phenols  Flavanoids  \
0    14.23  2.43               15.6        127           2.80        3.06   
1    13.20  2.14               11.2        100           2.65        2.76   

   Nonflavanoid phenols  Color intensity   Hue  Proline  
0                  0.28             5.64  1.04     1065  
1                  0.26             4.38  1.05     1050

In [60]:
X.shape,y.shape

((178, 10), (178,))

In [61]:
import torch

In [62]:
type(X)

pandas.core.frame.DataFrame

In [63]:
type(X.values)

numpy.ndarray

In [64]:
X=torch.tensor(X.values,dtype=torch.float32)
y=torch.tensor(y.values,dtype=torch.int64)

In [65]:
y

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [66]:
y-1

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [67]:
y=y-1

In [17]:
dataset=torch.utils.data.TensorDataset(X,y)

In [18]:
len(dataset)

178

In [19]:
dataset[0]

(tensor([1.4230e+01, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00, 3.0600e+00,
         2.8000e-01, 5.6400e+00, 1.0400e+00, 1.0650e+03]), tensor(0))

In [20]:
n_train=int(len(dataset)*0.6)
n_val=int(len(dataset)*0.2)
n_test=len(dataset)-n_train-n_val
n_train,n_val,n_test

(106, 35, 37)

In [21]:
torch.manual_seed(0)
train,val,test=torch.utils.data.random_split(dataset,[n_train,n_val,n_test])

In [22]:
import pytorch_lightning as pl

In [23]:
pl.__version__

'0.7.1'

In [24]:
import torch.nn as nn
import torch.nn.functional as F

In [25]:
from pytorch_lightning import Trainer

In [26]:
class Net(pl.LightningModule):
  def __init__(self,input_size=10,hidden_size=5,output_size=3,batch_size=10):
    super(Net,self).__init__()
    self.fc1=nn.Linear(input_size,hidden_size)
    self.fc2=nn.Linear(hidden_size,output_size)
    self.batch_size=batch_size

  def forward(self,x):
    x=self.fc1(x)
    x=F.relu(x)
    x=self.fc2(x)
    return x
  def lossfun(self,y,pred):
    return F.cross_entropy(y,pred)
  def configure_optimizers(self):
    return torch.optim.SGD(self.parameters(),lr=0.1)

  def train_dataloader(self):
    return torch.utils.data.DataLoader(train,self.batch_size,shuffle=True)
  def training_step(self,batch,batch_nb):
    X,y=batch
    output=self.forward(X)
    loss=self.lossfun(output,y)
    results={"loss":loss}
    return results

  def val_dataloader(self):
    return torch.utils.data.DataLoader(val,self.batch_size)
  def validation_step(self,batch,batch_nb):
    X,y=batch
    output=self.forward(X)
    loss=self.lossfun(output,y)
    pred=torch.argmax(output,dim=1)
    acc=torch.sum(pred==y)/len(y)
    results={"val_loss":loss,"val_acc":acc}
    return results
  def validation_end(self,outputs):
    avg_loss=torch.stack([x["val_loss"] for x in outputs]).mean()
    avg_acc=torch.stack([x["val_acc"] for x in outputs]).mean()
    results={"val_loss":avg_loss,"val_acc":avg_acc}
    return results
  
  def test_dataloader(self):
    return torch.utils.data.DataLoader(test,self.batch_size)
  def test_step(self,batch,batch_nb):
    X,y=batch
    output=self.forward(X)
    loss=self.lossfun(output,y)
    pred=torch.argmax(output,dim=1)
    acc=torch.sum(pred==y)/len(y)
    results={"test_loss":loss,"test_acc":acc}
    return results
  def test_end(self,outputs):
    avg_loss=torch.stack([x["test_loss"] for x in outputs]).mean()
    avg_acc=torch.stack([x["test_acc"] for x in outputs]).mean()
    results={"test_loss":avg_loss,"test_acc":avg_acc}
    return results

In [27]:
torch.manual_seed(0)
net=Net()
trainer=Trainer(max_epochs=30)
trainer.fit(net)

Validation sanity check:   0%|          | 0/5 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

1

In [28]:
trainer.test()

Testing:   0%|          | 0/4 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
TEST RESULTS
{}
----------------------------------------------------------------------------------------------------


In [29]:
trainer.callback_metrics

{'epoch': 29,
 'loss': 1.117541790008545,
 'test_acc': 0.44285714626312256,
 'test_loss': 1.0815160274505615,
 'val_acc': 0.40000003576278687,
 'val_loss': 1.0814515352249146}

In [30]:
class TrainNet(pl.LightningModule):
  def train_dataloader(self):
    return torch.utils.data.DataLoader(train,self.batch_size,shuffle=True)
  def training_step(self,batch,batch_nb):
    X,y=batch
    output=self.forward(X)
    loss=self.lossfun(output,y)
    results={"loss":loss}
    return results

In [31]:
class ValidationNet(pl.LightningModule):
  def val_dataloader(self):
    return torch.utils.data.DataLoader(val,self.batch_size)
  def validation_step(self,batch,batch_nb):
    X,y=batch
    output=self.forward(X)
    loss=self.lossfun(output,y)
    pred=torch.argmax(output,dim=1)
    acc=torch.sum(pred==y)/len(y)
    results={"val_loss":loss,"val_acc":acc}
    return results
  def validation_end(self,outputs):
    avg_loss=torch.stack([x["val_loss"] for x in outputs]).mean()
    avg_acc=torch.stack([x["val_acc"] for x in outputs]).mean()
    results={"val_loss":avg_loss,"val_acc":avg_acc}
    return results

In [32]:
class TestNet(pl.LightningModule):
  def test_dataloader(self):
    return torch.utils.data.DataLoader(test,self.batch_size)
  def test_step(self,batch,batch_nb):
    X,y=batch
    output=self.forward(X)
    loss=self.lossfun(output,y)
    pred=torch.argmax(output,dim=1)
    acc=torch.sum(pred==y)/len(y)
    results={"test_loss":loss,"test_acc":acc}
    return results
  def test_end(self,outputs):
    avg_loss=torch.stack([x["test_loss"] for x in outputs]).mean()
    avg_acc=torch.stack([x["test_acc"] for x in outputs]).mean()
    results={"test_loss":avg_loss,"test_acc":avg_acc}
    return results

In [33]:
class Net(TrainNet,ValidationNet,TestNet):
  def __init__(self,input_size=10,hidden_size=5,output_size=3,batch_size=10):
    super(Net,self).__init__()
    self.fc1=nn.Linear(input_size,hidden_size)
    self.fc2=nn.Linear(hidden_size,output_size)
    self.batch_size=batch_size

  def forward(self,x):
    x=self.fc1(x)
    x=F.relu(x)
    x=self.fc2(x)
    return x
  def lossfun(self,y,pred):
    return F.cross_entropy(y,pred)
  def configure_optimizers(self):
    return torch.optim.SGD(self.parameters(),lr=0.1)

In [34]:
torch.manual_seed(0)
net=Net()
trainer= Trainer(max_epochs=50)
trainer.fit(net)

Validation sanity check:   0%|          | 0/5 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

1

In [36]:
trainer.test()
trainer.callback_metrics

Testing:   0%|          | 0/4 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
TEST RESULTS
{}
----------------------------------------------------------------------------------------------------


{'epoch': 49,
 'loss': 1.1040228605270386,
 'test_acc': 0.44285714626312256,
 'test_loss': 1.0807652473449707,
 'val_acc': 0.40000003576278687,
 'val_loss': 1.082872986793518}

# バッチノーマライゼーション後

In [37]:
class Net(TrainNet,ValidationNet,TestNet):
  def __init__(self,input_size=10,hidden_size=5,output_size=3,batch_size=10):
    super(Net,self).__init__()
    self.fc1=nn.Linear(input_size,hidden_size)
    self.fc2=nn.Linear(hidden_size,output_size)
    self.batch_size=batch_size
    self.bn=nn.BatchNorm1d(input_size)
  def forward(self,x):
    x=self.bn(x)
    x=self.fc1(x)
    x=F.relu(x)
    x=self.fc2(x)
    return x
  def lossfun(self,y,pred):
    return F.cross_entropy(y,pred)
  def configure_optimizers(self):
    return torch.optim.SGD(self.parameters(),lr=0.1)

In [38]:
torch.manual_seed(0)
net=Net()
trainer= Trainer(max_epochs=50)
trainer.fit(net)

Validation sanity check:   0%|          | 0/5 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

Validating:   0%|          | 0/4 [00:00<?, ?it/s]

1

In [39]:
trainer.test()
trainer.callback_metrics

Testing:   0%|          | 0/4 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
TEST RESULTS
{}
----------------------------------------------------------------------------------------------------


{'epoch': 49,
 'loss': 0.051975831389427185,
 'test_acc': 1.0,
 'test_loss': 0.06410209834575653,
 'val_acc': 0.925000011920929,
 'val_loss': 0.09756729006767273}

# パラメータ保存

In [41]:
torch.save(net.state_dict(),"wine.pt")

In [42]:
net=Net()

In [46]:
net.fc1.weight

Parameter containing:
tensor([[ 0.2589,  0.2264,  0.2442,  0.2812, -0.0810,  0.1391,  0.2817,  0.1046,
          0.3161,  0.1640],
        [ 0.1966, -0.1107,  0.1517,  0.0363, -0.0755, -0.1783, -0.1774, -0.2433,
          0.2123,  0.2248],
        [-0.0360, -0.1830,  0.2444,  0.2022,  0.0235, -0.1493,  0.2906,  0.1293,
         -0.2401,  0.3027],
        [ 0.2401, -0.1153,  0.1778, -0.1797, -0.0496,  0.2685,  0.0131, -0.2236,
         -0.1057, -0.0858],
        [-0.0610,  0.0303,  0.2925,  0.0169, -0.1953,  0.0162,  0.1516,  0.1569,
         -0.2890, -0.0566]], requires_grad=True)

In [47]:
net.load_state_dict(torch.load("wine.pt"))

<All keys matched successfully>

In [48]:
net.fc1.weight

Parameter containing:
tensor([[-6.4216e-01, -2.9682e-01,  3.8889e-01, -2.7576e-01, -1.6168e-01,
          2.1542e-01, -2.1160e-01, -1.6256e-01,  2.2812e-01, -5.5664e-01],
        [-5.2270e-01, -5.1049e-01,  2.2277e-01,  4.6072e-02, -1.4593e-01,
         -1.6255e-01,  1.6577e-01, -5.0242e-01,  3.0085e-01, -7.5873e-01],
        [ 1.1511e-01,  2.2154e-01,  6.1802e-03,  5.6500e-02, -8.1684e-02,
         -4.4245e-01,  2.6993e-01,  1.0958e-01, -4.6543e-01, -1.6251e-01],
        [-2.7684e-01,  3.2316e-01, -7.0351e-04, -2.2252e-01, -1.7115e-01,
         -8.6096e-01, -6.7532e-02,  6.5556e-01, -3.5754e-01, -1.7708e-01],
        [ 2.5748e-02, -2.1194e-02,  1.9073e-01, -2.0278e-01, -2.6584e-01,
         -8.7910e-01,  2.8585e-01,  4.6767e-01, -3.6880e-01, -2.4474e-01]],
       requires_grad=True)

# 予測

In [68]:
outputs=net(X)
outputs[0]

tensor([ 2.2173, -1.0217, -1.5283], grad_fn=<SelectBackward0>)

In [69]:
torch.argmax(outputs[0])

tensor(0)

In [70]:
y[0]

tensor(0)